// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// HelloWorldResponse defines model for HelloWorldResponse.
type HelloWorldResponse struct {
	Country string `json:"country"`
	Hello   string `json:"hello"`
}

// GetHelloWorldParams defines parameters for GetHelloWorld.
type GetHelloWorldParams struct {
	// Country Country to say hello to
	Country *string `form:"country,omitempty" json:"country,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a hello world
	// (GET /hello/world)
	GetHelloWorld(ctx echo.Context, params GetHelloWorldParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHelloWorld converts echo context to params.
func (w *ServerInterfaceWrapper) GetHelloWorld(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHelloWorldParams
	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameter("form", true, false, "country", ctx.QueryParams(), &params.Country)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter country: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHelloWorld(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/hello/world", wrapper.GetHelloWorld)

}

type GetHelloWorldRequestObject struct {
	Params GetHelloWorldParams
}

type GetHelloWorldResponseObject interface {
	VisitGetHelloWorldResponse(w http.ResponseWriter) error
}

type GetHelloWorld200JSONResponse HelloWorldResponse

func (response GetHelloWorld200JSONResponse) VisitGetHelloWorldResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get a hello world
	// (GET /hello/world)
	GetHelloWorld(ctx context.Context, request GetHelloWorldRequestObject) (GetHelloWorldResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetHelloWorld operation middleware
func (sh *strictHandler) GetHelloWorld(ctx echo.Context, params GetHelloWorldParams) error {
	var request GetHelloWorldRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHelloWorld(ctx.Request().Context(), request.(GetHelloWorldRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHelloWorld")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHelloWorldResponseObject); ok {
		return validResponse.VisitGetHelloWorldResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
